# Generated by Django 2.1.5 on 2019-01-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='money',
        ),
    ]
