# Generated by Django 2.1.5 on 2019-01-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_product_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
