# Generated by Django 2.1.5 on 2019-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('amount', models.CharField(max_length=128)),
            ],
        ),
    ]
